"""
Models for the Signals app.
Handles trading signals and indicators.
"""
from django.db import models
from stocks.models import Stock


class Signal(models.Model):
    """
    Trading signals generated by the signal engine.
    Prevents duplicate signals with time-based constraints.
    """
    SIGNAL_TYPES = [
        ('BUY', 'Buy Signal'),
        ('SELL', 'Sell Signal'),
        ('ALERT', 'Price Alert'),
    ]

    stock = models.ForeignKey(
        Stock,
        on_delete=models.CASCADE,
        related_name='signals'
    )
    signal_type = models.CharField(
        max_length=10,
        choices=SIGNAL_TYPES,
        help_text="Type of signal"
    )
    reason = models.TextField(
        help_text="Human-readable explanation for the signal"
    )
    confidence_score = models.IntegerField(
        help_text="Confidence score (0-100%)"
    )
    indicator_details = models.JSONField(
        default=dict,
        blank=True,
        help_text="Technical indicator details (MA values, volume, etc.)"
    )
    is_notified = models.BooleanField(
        default=False,
        help_text="Whether users have been notified"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['stock', 'signal_type']),
            models.Index(fields=['-created_at']),
            models.Index(fields=['is_notified']),
        ]

    def __str__(self):
        return f"{self.stock.symbol} - {self.signal_type} ({self.confidence_score}%)"

    @classmethod
    def get_recent_signal(cls, stock, signal_type, hours=1):
        """
        Check if a similar signal was created recently (prevents duplicates).
        """
        from django.utils import timezone
        from datetime import timedelta
        
        cutoff_time = timezone.now() - timedelta(hours=hours)
        return cls.objects.filter(
            stock=stock,
            signal_type=signal_type,
            created_at__gte=cutoff_time
        ).exists()
