# Generated by Django 4.2.13 on 2026-07-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('holding_days', models.IntegerField(default=10, help_text='Number of trading days to hold each simulated position')),
                ('total_stocks', models.IntegerField(default=0)),
                ('total_trades', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('EMA_CROSS', 'EMA Cross (Golden/Death)'), ('MACD_CROSS', 'MACD Crossover'), ('RSI_MEAN_REVERSION', 'RSI Mean Reversion'), ('RSI_DIVERGENCE', 'RSI Divergence'), ('DOW_THEORY', 'Dow Theory'), ('WEEKLY_SMA_CROSS', 'Weekly SMA Cross'), ('VOLUME_BREAKOUT', 'Volume Spike Breakout')], max_length=30)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0, help_text='Percentage of winning trades (0-100)')),
                ('avg_return_pct', models.FloatField(default=0.0, help_text='Mean percentage return across all trades')),
                ('avg_holding_days', models.FloatField(default=0.0, help_text='Mean actual holding period in trading days')),
                ('max_drawdown_pct', models.FloatField(default=0.0, help_text='Worst single-trade percentage loss')),
                ('best_trade_pct', models.FloatField(default=0.0, help_text='Best single-trade percentage gain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='backtesting.backtestrun')),
            ],
            options={
                'ordering': ['signal_type', 'direction'],
                'unique_together': {('run', 'signal_type', 'direction')},
            },
        ),
    ]
