# Generated by Django 4.2.13 on 2026-07-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestresult',
            name='signal_type',
            field=models.CharField(choices=[('EMA_CROSS', 'EMA Cross (Golden/Death)'), ('MACD_CROSS', 'MACD Crossover'), ('RSI_MEAN_REVERSION', 'RSI Mean Reversion'), ('RSI_DIVERGENCE', 'RSI Divergence'), ('DOW_THEORY', 'Dow Theory'), ('WEEKLY_SMA_CROSS', 'Weekly SMA Cross'), ('VOLUME_BREAKOUT', 'Volume Spike Breakout'), ('CONFLUENCE_SCORE', 'Confluence Score')], max_length=30),
        ),
    ]
