# Generated by Django 5.0.1 on 2026-05-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock symbol/ticker (e.g., NABIL)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full company name', max_length=200)),
                ('sector', models.CharField(blank=True, help_text='Industry sector', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current stock price', max_digits=10)),
                ('volume', models.BigIntegerField(default=0, help_text='Current trading volume')),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage change from previous close', max_digits=6)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Market capitalization', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether stock is actively traded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='stocks_stoc_symbol_3e1bfd_idx'), models.Index(fields=['is_active'], name='stocks_stoc_is_acti_df6b74_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Trading date')),
                ('open_price', models.DecimalField(decimal_places=2, help_text='Opening price', max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, help_text='Highest price of the day', max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, help_text='Lowest price of the day', max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, help_text='Closing price', max_digits=10)),
                ('volume', models.BigIntegerField(default=0, help_text='Trading volume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', '-date'], name='stocks_stoc_stock_i_6df97d_idx'), models.Index(fields=['date'], name='stocks_stoc_date_f34fed_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
