# Generated by Django 4.2.13 on 2026-07-19 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, choices=[('Commercial Bank', 'Commercial Bank'), ('Development Bank', 'Development Bank'), ('Finance', 'Finance'), ('Microfinance', 'Microfinance'), ('Hydropower', 'Hydropower'), ('Life Insurance', 'Life Insurance'), ('Non-Life Insurance', 'Non-Life Insurance'), ('Hotel & Tourism', 'Hotel & Tourism'), ('Manufacturing and Processing', 'Manufacturing and Processing'), ('Trading', 'Trading'), ('Investment', 'Investment'), ('Mutual Fund', 'Mutual Fund'), ('Others', 'Others')], default='', help_text='NEPSE sector classification', max_length=40),
        ),
        migrations.CreateModel(
            name='FundamentalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the snapshot was recorded or published')),
                ('eps', models.DecimalField(blank=True, decimal_places=2, help_text='Earnings Per Share (Rs.)', max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Price to Earnings ratio', max_digits=10, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, help_text='Book Value per share (Rs.)', max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Dividend yield percentage', max_digits=6, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=2, help_text='Return on Equity percentage', max_digits=8, null=True)),
                ('cd_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Credit to Deposit ratio (banks only)', max_digits=6, null=True)),
                ('npl_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Non-Performing Loan ratio (banks only)', max_digits=6, null=True)),
                ('capital_adequacy_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Capital Adequacy ratio (banks only)', max_digits=6, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
