# Generated by Django 4.2.13 on 2026-07-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_sector_fundamentalsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MONETARY_POLICY', 'Monetary Policy'), ('DIVIDEND', 'Dividend Announcement'), ('AGM', 'Annual General Meeting (AGM)'), ('BOOK_CLOSURE', 'Book Closure'), ('EARNINGS', 'Earnings Report'), ('OTHER', 'Other Event')], max_length=50)),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('stock', models.ForeignKey(blank=True, help_text="Null means it's a market-wide event (e.g. Monetary Policy)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stocks.stock')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
