# Generated by Django 5.0.1 on 2026-05-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy Signal'), ('SELL', 'Sell Signal'), ('ALERT', 'Price Alert')], help_text='Type of signal', max_length=10)),
                ('reason', models.TextField(help_text='Human-readable explanation for the signal')),
                ('confidence_score', models.IntegerField(help_text='Confidence score (0-100%)')),
                ('indicator_details', models.JSONField(blank=True, default=dict, help_text='Technical indicator details (MA values, volume, etc.)')),
                ('is_notified', models.BooleanField(default=False, help_text='Whether users have been notified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', 'signal_type'], name='signals_sig_stock_i_a243e3_idx'), models.Index(fields=['-created_at'], name='signals_sig_created_996097_idx'), models.Index(fields=['is_notified'], name='signals_sig_is_noti_310f9f_idx')],
            },
        ),
    ]
